import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === 'production';

const concatStyles = () => {
  try {
    const styleFiles = [
      // Core Styles
      'src/app/styles/base.css',
      'src/app/styles/layout.css',
      'src/app/styles/components.css',

      // Module Styles
      'src/modules/date-progress/styles.css',
      'src/modules/contribution-graph/styles.css',
      'src/modules/todo/styles.css',
      'src/modules/recent-files/styles.css',
      'src/modules/random-note/styles.css',
      'src/modules/tmp-note/styles.css',
    ];

    let combinedCss = '';
    for (const file of styleFiles) {
      if (fs.existsSync(file)) {
        combinedCss += fs.readFileSync(file, 'utf8') + '\n';
      } else {
        console.warn(`Style file not found: ${file}`);
      }
    }

    fs.writeFileSync('build/styles.css', combinedCss);
    console.log('Concatenated styles to build/styles.css');
  } catch (e) {
    console.error('Error concatenating styles:', e);
  }
};

const copyFiles = () => {
  try {
    // Create build folder if not exists
    if (!fs.existsSync('build')) {
      fs.mkdirSync('build');
    }

    // Copy manifest.json
    fs.copyFileSync('manifest.json', 'build/manifest.json');
    console.log('Copied manifest.json to build/');

    // Concatenate styles instead of copying global.css
    concatStyles();
  } catch (e) {
    console.error('Error copying files:', e);
  }
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/app/main.tsx'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'build/main.js',
  plugins: [
    {
      name: 'copy-static-files',
      setup(build) {
        build.onEnd(() => {
          copyFiles();
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
